config/routes.rb
Rails.application.routes.draw do
  resources :admins

  resources :categories do
    resource :works, only: [:index, :new, :create]
  end

  resources :works, only: [:show, :edit, :update, :destroy]

  post '/send_mail' => 'contact#send_mail', as: :send_mail

  get '/home' => 'home#index', as: :home

  get '/about' => 'about#index', as: :about

  get '/services' => 'services#index', as: :services

  root 'admins#authorize', as: 'authorize'

  get '/contact' => 'contact#index', as: :contact

  get '*path' => redirect('/home')
end

app/models/work.rb
class Work < ApplicationRecord
  attr_accessor :place
  validates :place, presence: true,
                    numericality: { greater_than: 0 }
  mount_uploader :image, WorkUploader
  belongs_to :category
end

app/controllers/works_controller.rb
class WorksController < ApplicationController
  before_action :find_work, only: [:show, :destroy, :edit, :update]

  def index
    @works = Work.all
  end

  def show
  end

  def new
    @category = Category.find(params[:category_id])
    @work = Work.new
  end

  def create
    @category = Category.find(params[:category_id])
    @work = @category.works.create(image_info)
    if @work
      save_place(@category, @work, @work.place.to_i)
      flash[:success] = 'work uploaded and saved *nice*'
      redirect_to category_path(params[:category_id])
    else
      flash.now[:error] = "invalid input, no upload occured :("
      render 'new'
    end
  end

  def destroy
    id = @work.category.id

    # the deleted work's position is recorded, the work is destroyed, and THEN all highert works form the same cetegory are shuffled down as far as they can be shuffled down
    deleted_position = @work.position
    @work.destroy
    work_shuffle_down(deleted_position, id)
    flash[:success] = 'work deleted successfully'
    redirect_to category_path(id)
  end

  def edit
  end

  def update
    # record the old position and check if the inputs make sense
    # if so, save the works being updated to the new position, shuffle all the worksdown that can be shuffled down and rerout to the page for the current category
    old_place = @work.position
    if @work.update_attributes(image_info)
      save_place(@work.category, @work, @work.place.to_i)
      work_shuffle_down(old_place, @work.category.id)
      flash[:success] = 'work updated'
      redirect_to category_path(@work.category_id)
    else
      flash.now[:error] = 'invalid input'
      render 'edit'
    end
  end

  # ----------------------------------

  private

  def find_work
    @work = Work.find(params[:id])
  end

  def image_info
    params.require(:work).permit(:title, :image, :caption, :place)
  end
end

app/helpers/works_helper.rb
module WorksHelper
  def save_place(cat, work, place)
    # recurisve function, pushes the current place down untill it is as low as possible wirhout conflicting, OR, if there is a conflict, pushes it up
    prev_slot = cat.works.where(position: place - 1)
    if prev_slot.empty? && place > 1
      # if the place is not the first possible place and the previous place slot isn't empty, it should try to slot the category in at the previous place
      if place > 1
        save_place(cat, work, place - 1)
      end
    else
      # otherwise, if the place has been taken it should increment the place of the work with the matching place and keep trying to save it untill we run out of place conflicts, then save the origional place as intended.
      same_place = cat.works.where(position: place)
      if !same_place.empty?
        save_place(cat, same_place.take, place + 1)
      end
      work.update_attribute(:position, place)
    end
  end

  def work_shuffle_down(position, id)
    # grabs an array of all works in this category with a higher position than the passed in position (orderd in ascending position order)
    # re-saves the position of each work IN ORDER
    cat = Category.find(id)
    cat.works.where("position > ?", position)
      .order(position: :asc)
      .each do |work|
        save_place(cat, work, work.position)
      end
  end
end

app/views/works/_works_form.html.erb
<%= form_for [@category, @work] do |f| %>
  <div class="form-group">
    <%= f.label 'Work Name' %>
    <%= f.text_field :title, value: @work.title %>
    <br />
  </div>
  <div class="form-group">
    <%= f.label 'Image:' %>
    <%= f.file_field :image, class: 'file-upload', value: @work.image.url %>
    <%= render '/shared/hidden_loader' %>
    <br />
  </div>
  <div class="form-group">
    <%= f.label 'Caption:' %>
    <%= f.text_area :caption, rows: 8, cols: 40, value: @work.caption %>
    <br /><br />
  <div class="form-group">
    <%= f.label 'Place (1 = first place, 2 = second, etc...):' %>
    <%= f.number_field :place, value: @work.position || 1 %>
    <br /><br />
  </div>
  <div class="position-relative">
    <%= f.submit 'Save changes' %>
    <div class="overlay white opaque hover-reveal super-hidden" id="upload-helper">
      Wait, file still uploading...
    </div>
  </div>

<% end %>
<br />

app/views/works/edit.html.erb
<h1>Edit Artwork</h1>

<%= render '/works/works_form' %>

<%= link_to 'Back to gallery', work_path(@work.id) %>

app/views/works/new.html.erb
<h1>Upload Artwork</h1>

<%= render '/works/works_form' %>

<%= link_to "Back to #{@category.title}", category_path(@category.id) %>