config/routes.rb
Rails.application.routes.draw do
  resources :admins

  resources :categories do
    resource :works, only: [:index, :new, :create]
  end

  resources :works, only: [:show, :edit, :update, :destroy]

  post '/send_mail' => 'contact#send_mail', as: :send_mail

  get '/home' => 'home#index', as: :home

  get '/about' => 'about#index', as: :about

  get '/services' => 'services#index', as: :services

  root 'admins#authorize', as: 'authorize'

  get '/contact' => 'contact#index', as: :contact

  get '*path' => redirect('/home')
end

app/views/shared/_flashes.html.erb
<% flash.each do |name, message| %>
  <% if message.is_a? String %>
    <div class="flash text-light text-center <%= name %>">
      <h5>
        <%= message %>
      </h5>
    </div>
  <% end %>
<% end %>

app/views/shared/_footer.html.erb
<footer>
  <ul class="pl-0 smallish details">
    <li><h4 class="text-uppercase m-0">Floral Design</h4></li>
    <li>
      <div class="text-muted">
        kazpetrulyte@outlook.com
      </div>
    </li>
    <li>
      <div class="text-muted">
        0422 110 672
      </div>
    </li>
    <li>
      <ul class="icons">
        <li>
          <a class="subtle text-muted" href="https://www.facebook.com/flowersbykaz/" target="_blank"><i class="fab fa-facebook-square"></i></a>
        </li>
        <li>
          <a class="subtle text-muted" href="https://www.instagram.com/flowersbykaz/" target="_blank"><i class="fab fa-instagram"></i></a>
        </li>
        <li>
          <a class="subtle text-muted" href="mailto:kazpetrulyte@outlook.com" target="_blank"><i class="fas fa-envelope-square"></i></a>
        </li>
      </ul>
    </li>
  </ul>
  <div>
    <span class="text-secondary text-small">&copy;Flowers By Kaz 2018</span>
  </div>
</footer>

app/views/shared/_head.html.erb
<title>FlowersByKaz</title>
<%= csrf_meta_tags %>

<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
<script defer src="https://use.fontawesome.com/releases/v5.0.6/js/all.js"></script>
<link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">

app/views/shared/_header.html.erb
<div class="header">
    <%= render '/shared/nav_bar' %>
    <div class="clearfix">

    </div>
</div>

app/views/shared/_hidden_loader.html.erb
<div class="loader-wrapper hidden">
  <h4>Image uploading please wait...</h4>
  <div class="lds-roller"><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div></div>
</div>

app/views/shared/_logo.html.erb
<a class="brand m-0 p-0" href="#"><img src="<%= image_path('card_front.png') %>" class="d-inline-block align-top" alt=""></a>

app/views/shared/_nav_bar.html.erb
<nav class="navbar navbar-expand-lg navbar-light pl-0">



  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link delicate pl-0" href="<%= home_path %>">Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link delicate" href="<%= about_path %>">About</a>
      </li>
      <li class="nav-item">
        <a class="nav-link delicate" href="<%= categories_path %>">Portfolio</a>
      </li>
      <li class="nav-item">
        <a class="nav-link delicate" href="<%= services_path %>">Services</a>
      </li>
      <li class="nav-item">
        <a class="nav-link delicate" href="<%= contact_path %>">Contact</a>
      </li>
      <% if session[:admin] %>
        <li class="nav-item">
          <%= button_to 'Create New Category', new_category_path, method: :get %>
        </li>
        <li class="nav-item">
          <%= button_to 'Sign out', "/admins/#{session[:admin]}", method: :delete %>
        </li>
      <% end %>
    </ul>
  </div>

</nav>