config/routes.rb
Rails.application.routes.draw do
  resources :admins

  resources :categories do
    resource :works, only: [:index, :new, :create]
  end

  resources :works, only: [:show, :edit, :update, :destroy]

  post '/send_mail' => 'contact#send_mail', as: :send_mail

  get '/home' => 'home#index', as: :home

  get '/about' => 'about#index', as: :about

  get '/services' => 'services#index', as: :services

  root 'admins#authorize', as: 'authorize'

  get '/contact' => 'contact#index', as: :contact

  get '*path' => redirect('/home')
end

app/models/category.rb
class Category < ApplicationRecord
  validates :title, :presence => true;
  attr_accessor :place
  validates :place, presence: true,
                    numericality: { greater_than: 0 }


  mount_uploader :image, CategoryUploader
  has_many :works
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :find_category, only: [:edit, :show, :update, :destroy]

  def index
    @categories = Category.order(:position)
  end

  def show
    @works = @category.works.order(:position)
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_info)
    if @category.save
      save_cat_place(@category, @category.place.to_i)
      flash[:success] = 'Category created *nice*'
      redirect_to categories_path
    else
      flash.now[:error] = "invalid input, no upload occured :("
      render 'new'
    end
  end

  def edit
  end

  def update
    # record the old position and check if the inputs make sense
    # if so, save the category being updated to the new position, shuffle all the categories down that can be shuffled down and rerout to the portfolio page
    old_position = @category.position
    if @category.update_attributes(category_info)
      save_cat_place(@category, @category.place.to_i)
      cat_shuffle_down(old_position)
      flash[:success] = 'category successfully updated'
      redirect_to categories_path
    else
      flash.now[:error] = 'that input was invalid'
      render 'edit'
    end
  end

  def destroy
    @category.works.each do |work|
      work.destroy
    end

    # the deleted categorie's position is recorded, the category is destroyed, and THEN all higher categories are shuffled down as far as they can be shuffled down
    deleted_position = @category.position
    @category.destroy
    cat_shuffle_down(deleted_position)

    flash[:success] = 'category deleted'
    redirect_to categories_path
  end

  private

  def find_category
    @category = Category.find(params[:id])
  end

  def category_info
    params.require(:category).permit(:title, :image, :place)
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
  def save_cat_place(cat, place)
    # recurisve function, pushes the current place down untill it is as low as possible wirhout conflicting, OR, if there is a conflict, pushes it up

    prev_slot = Category.where(position: place - 1)
    if prev_slot.empty? && place > 1
      # if the place is not the first possible place and the previous place slot isn't empty, it should try to slot the category in at the previous place
      if place > 1
        save_cat_place(cat, place - 1)
      end
    else
      # otherwise, if the current place has been taken it should increment the place of the work with the matching place and keep trying to save it untill we run out of place conflicts, then save the origional place as intended.
      same_place = Category.where(position: place)
      if !same_place.empty?
        save_cat_place(same_place.take, place + 1)
      end
      cat.update_attribute(:position, place)
    end
  end

  def cat_shuffle_down(position)
    # grabs an array of all cats with a higher position than the passed in positione (orderd in ascending position order)
    # re-saves the position of each category IN ORDER
    Category.where("position > ?", position)
      .order(position: :asc)
      .each do |cat|
        save_cat_place(cat, cat.position)
      end
  end
end

app/views/categories/_category_form.html.erb
<%= form_for @category do |f| %>
  <div class="form-group">
    <%= f.label 'Category title (required):' %>
    <input type="text" name="category[title]" value="<%= @category.title %>" id="category_title" required>
    <br />
  </div>
  <div class="form-group">
    <%= f.label 'Category cover image:' %>
    <%= f.file_field :image, class: 'file-upload' %>
    <%= render '/shared/hidden_loader' %>
    <br />
  </div>
  <div class="form-group">
    <%= f.label 'Place, 1 = first place, 2 = second, etc...' %>
    <%= f.number_field :place, value: @category.position || 1 %>
    <br />
  </div>
    <div class="position-relative">
      <%= f.submit 'Save changes' %>
      <div class="overlay white opaque hover-reveal super-hidden" id="upload-helper">
        Wait, file still uploading...
      </div>
    </div>
<% end %>
<br />

app/views/categories/edit.html.erb
<h1>Edit <%= @category.title %>'s info</h1>

  <%= render '/categories/category_form' %>

<%= link_to 'Cancel', categories_path %>

app/views/categories/index.htm.erb
<h1>sdaasdas</h1>

app/views/categories/index.html.erb
<div class="row covers">
  <% @categories.each do |category| %>

    <div class="col-md-3 col-sm-4 col-6 covers-col position-relative p-2">
      <a href="<%= category_path(category.id) %>" class="subtle">
        <div class="position-relative loading-overlay-holder">
          <div class="square-img-wrapper opaque" data-url="<%= image_url(category.image.url) %>"></div>
          <div class="overlay d-flex align-items-center justify-content-center loader-holder">
            <div class="lds-spinner"><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div></div>
          </div>
        </div>
      <div class="container-fluid pt-1"></a>
        <h5 class="delicate text-center text-muted"><%= category.title %></h5>
      </div>
      <% if session[:admin] %>
        <div class="admin-box">
          <h4>Position: <%= category.position %></h4>
          <%= button_to 'Delete', "/categories/#{category.id}", method: :delete %>
          <%= button_to 'Edit', edit_category_path(category.id), method: :get %>
        </div>
      <% else %>
        <a href="<%= category_path(category.id) %>" class="subtle"><div class="overlay white opaque hover-reveal"></div></a>
      <% end %>
    </div>
  <% end %>
</div>

<div class="row breadcrumbs">
  <div class="col-12">
    <% if session[:admin] %>
      <div class="row breadcrumbs">
        <%= link_to 'Create New Category', new_category_path, method: :get %>
      </div>
    <% end %>
  </div>
</div>

app/views/categories/new.html.erb
<h1>Create new Category</h1>

<%= render '/categories/category_form' %>

<a href="javascript:history.back()"> Cancel</a>

app/views/categories/show.html.erb
<div class="row covers">
  <% count = 1 %>

  <% @works.each do |work| %>

  <div class="col-lg-2 col-md-3 col-sm-4 col-6 covers-col p-1">
      <div class="position-relative loading-overlay-holder">
        <div class="container-fluid position-relative p-0">
          <div class="overlay white opaque hover-reveal work-overlay" data-title="<%= work.title %>" data-caption="<%= work.caption %>" data-url="<%= image_url(work.image.url) %>" data-number="<%= count %>" id="work-<%= count %>"></div>
          <div class="square-img-wrapper opaque" data-url="<%= image_url(work.image.url) %>">
          </div>
        </div>
        <div class="overlay d-flex align-items-center justify-content-center loader-holder">
          <div class="lds-roller"><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div></div>
        </div>
      </div>
    <% if session[:admin] %>
      <h4>Position: <%= work.position %></h4>
       <%= button_to 'Delete', "/works/#{work.id}", method: :delete %>
       <%= button_to 'Edit', edit_work_path(work.id), method: :get %>
    <% end %>
  </div>

    <% count += 1 %>
  <% end %>

</div>

<div class="row breadcrumbs">
  <div class="col-12">
    <a href="<%= categories_path%>" class="subtle text-muted"><h6 class="delicate text-uppercase">Return to Portfolio</h6></a>
    <% if session[:admin] %>
      <div class="row breadcrumbs">
        <%= link_to "Upload new artwork to #{@category.title}", new_category_works_path(@category.id) %>
      </div>
    <% end %>
  </div>
</div>

<div class="overlay black opaque hidden work-show text-light">
  <div class="work-overlay-clear">
    <i class="far fa-times-circle"></i>
  </div>
  <div class="container-fluid d-flex align-items-center justify-content-center p-0" id="work-holder">
    <div class="row justify-content-center align-items-stretch">
      <div class="col-1 work-nav prev p-0">
          <i class="fa fa-angle-left"></i>
      </div>
      <div class="col-md-8 col-9 position-relative p-0">
        <%= image_tag 'default_work.jpg', class: 'img-fluid', id: 'work-image' %>
        <div class="overlay opaque hover-reveal work-overlay" id="work-info">
          <div id="info-container">
            <h5 id="work-title">if you can see this something went wrong</h5>
            <p class="smallish" id="work-description">if you can see this something went wrong</p>
          </div>
        </div>
      </div>
      <div class="col-1 work-nav next p-0">
          <i class="fa fa-angle-right"></i>
      </div>
    </div>
  </div>
</div>